server:
   port: 9090

spring:
   application:
      name: fuel-app-parser-service
   datasource:
      url: jdbc:mysql://@eu-cdbr-west-02.cleardb.net/heroku_cbd789b3d0712cf?useUnicode=yes&characterEncoding=UTF-8
      username: b18560def51940
      password: ca4c1855
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true

eureka:
   client:
      serviceUrl:
         defaultZone: https://e-petrol-eureka.herokuapp.com/eureka
   instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}